services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    ports:
      - "9200:9200" #http
      - "9300:9300" #tcp
    environment:
      - discovery.type=single-node
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always